rozciag/urls.py
from django.urls import path
from .views import wszystkie_wpisy, nowy_wpis, edytuj_wpis, usun_wpis, login_request, logout_request, filtrowanie


urlpatterns = [
    path('', nowy_wpis, name='home'),
    path('wszystkie/', wszystkie_wpisy, name='wszystkie_wpisy'),
    path('eksport/', filtrowanie, name='filtrowanie'),
    path('edytuj/<int:id>/',edytuj_wpis, name='edytuj_wpis'),
    path('usun/<int:id>/', usun_wpis, name='usun_wpis'),
    path('login/', login_request, name='login'),
    path('logout/', logout_request, name='logout'),
]

rozciagi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('rozciag.urls')),
]

rozciag/models.py
from django.db import models
from datetime import datetime
import socket
import getpass
from django.contrib.auth.models import User


class GrupaRobocza(models.Model):
    nazwa = models.CharField(max_length=15)
    aktywna = models.BooleanField(default=True)

    def __str__(self):
        return self.nazwa


class Narzedzia(models.Model):
    grupa = models.CharField(max_length=15)
    uwagi = models.CharField(max_length=150,null=True,blank=True)
    aktywny = models.BooleanField(default=True)

    def __str__(self):
        return self.grupa


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dzial = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.user.username


class Rozciagi(models.Model):

    hostname = socket.gethostname()
    login_username = getpass.getuser()
    user = User.username

    listy = (
        ('lista',"Lista połączeń"),
        ('zlecenie', "Zlecenie produkcyjne")
    )

    nr_zlecenia = models.CharField(max_length=10)#
    #nr_pozycji = models.DecimalField(max_digits=4,decimal_places=0)#
    nr_pozycji = models.CharField(max_length=200)#
    lista = models.CharField(max_length=15, default="lista", choices=listy)#
    nr_pracownika = models.DecimalField(max_digits=5,decimal_places=0)#
    rozciag = models.DecimalField(max_digits=5,decimal_places=0)#
    przekroj_przewodu = models.DecimalField(max_digits=4,decimal_places=2)#
    indeks_kontaktu = models.CharField(max_length=10)#
    poprawkowe = models.BooleanField(default=False)#
    narzedzia = models.CharField(max_length=20)#
    grupa_robocza = models.ForeignKey(GrupaRobocza, on_delete=models.CASCADE)#
    wysokosc = models.DecimalField(max_digits=4,decimal_places=2,default=0, blank=True, null=True)#
    data_serwis = models.DateTimeField('data serwis', blank=True, null=True)
    data_dodania = models.DateTimeField('data dodania',default=datetime.now)
    narzedzia_rodzaj = models.ForeignKey(Narzedzia, on_delete=models.CASCADE)#
    potwierdzenie = models.BooleanField(default=False)
    zalogowany_user = models.ForeignKey(Author, on_delete=models.CASCADE, blank=True, null=True)
    komputer_user = models.CharField(max_length=10,default=login_username)
    komputer = models.CharField(max_length=30,default=hostname)


    def __str__(self):
        return self.indeks_kontaktu

templates/rozciagi/base.html
<!doctype html>
<html lang="en">
    {% include "rozciagi/head.html" %}
    <body class="d-flex flex-column h-100 d-inline-block">
        {% include "rozciagi/header.html" %}
        {% include "rozciagi/messages.html" %}

        {% block content %}
        {% endblock content %}

        {% include "rozciagi/footer.html" %}
        {% include "rozciagi/scripts.html" %}
    </body>
</html>

templates/rozciagi/filter.html
{% extends 'rozciagi/base.html' %}
{% load bootstrap %}
{% block content %}
    <div class="container-fluid">
        <div class="card col-md-6 my-3 mx-auto">
            <div class="card-body">

                <form method="get">
                    <div class="form-row mb-3">
                        <div class="col">
                            <input class="form-control py-2 border" type="search" name="indeks_kontaktu_contains" placeholder="indeks kontaktu..." />
                        </div>
                    </div>
                    <div class="form-row mb-3">
                        <div class="col">
                            <input class="form-control py-2 border" type="search" name="numer_zlecenia_contains" placeholder="Numer zlecenia..." />
                        </div>
                    </div>
                    <div class="form-row mb-3">
                        <div class="col">
                            <input class="form-control py-2 border" type="search" name="pracownik_contains" placeholder="Pracownik..." />
                        </div>
                    </div>
                    <div class="form-row mb-3">
                        <div class="col">
                            <input class="form-control py-2 border" type="search" name="narzedzia_contains" placeholder="Narzedzia..." />
                        </div>
                    </div>
                    <div class="form-row mb-3">
                        <div class="col">
                            <input type="date" class="form-control" id="data_od" name="data_od" placeholder="Data wpisu od"  />
                        </div>
                        <div class="col">
                            <input type="date" class="form-control" id="data_do" name="data_do" placeholder="Data wpisu do"  />
                        </div>
                    </div>
                    <div class="form-row mb-3">
                        <div class="col">
                            <input type="date" class="form-control" id="data_serwis_od" name="data_serwis_od" placeholder="Data serwisu od"  />
                        </div>
                        <div class="col">
                            <input type="date" class="form-control" id="data_serwis_do" name="data_serwis_do" placeholder="Data serwisu do"  />
                        </div>
                    </div>
                    <input type="hidden" id="eksport" name="eksport" value="on">
                    <div class="form-row mb-3">
                        <div class="col">
                            <button type="submit" class="btn btn-primary">Zapisz</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>

{% endblock content %}

templates/rozciagi/footer.html
<!-- Footer -->
    <footer class="page-footer font-small unique-color-dark pt-4">
        <!-- Footer Elements -->
        <div class="container">
            <div class="row">
                <div class="col my-4 mx-auto">
                    {% if user.is_authenticated %}
                        Witaj <h5>{{user}}</h5>
                    {% else %}
                        Nie jesteś zalogowany!
                    {% endif %}
                </div>
                <div class="col my-4">
                    {% if user.is_authenticated %}
                        Masz Możliwość edycji lub usuwania wpisów. Możesz rówenież eksportować wybrane dane do pliku.
                    {% else %}
                        Nie będąc zalogowanym masz możliwość tylko dodać wpis lub przeglądać dane.
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- Footer Elements -->
        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">
            © 2020 Copyright: MK | Rimaster
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->

templates/rozciagi/form.html
{% extends 'rozciagi/base.html' %}
{% load bootstrap %}
{% block content %}
    <div class="container-fluid">
        <div class="card col-md-6 my-3 mx-auto">
            <div class="card-body">
                <form method="post" role="form" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row mb-3">
                        <div class="col">
                            {{ form.nr_zlecenia|bootstrap }}
                        </div>
                        <div class="col">
                            {{ form.indeks_kontaktu|bootstrap }}
                        </div>
                        <div class="col">
                            {{ form.poprawkowe|bootstrap }}
                        </div>
                    </div>
                    <div class="form-row mb-3">
                        <div class="col">
                            {{ form.nr_pozycji|bootstrap }}
                        </div>
                        <div class="col">
                            {{ form.lista|bootstrap }}
                        </div>
                    </div>
                    <div class="form-row mb-3">
                        <div class="col">
                            {{ form.przekroj_przewodu|bootstrap }}
                        </div>
                        <div class="col">
                            {{ form.rozciag|bootstrap }}
                        </div>
                        <div class="col">
                            {{ form.potwierdzenie|bootstrap }}
                        </div>
                    </div>
                    <div class="form-row mb-3">
                        <div class="col">
                            {{ form.narzedzia|bootstrap }}
                        </div>
                        <div class="col">
                            {{ form.narzedzia_rodzaj|bootstrap }}
                        </div>
                    </div>
                    <div class="form-row mb-3">
                        <div class="col">
                            {{ form.nr_pracownika|bootstrap }}
                        </div>
                        <div class="col">
                            {{ form.grupa_robocza|bootstrap }}
                        </div>
                    </div>
                    
                    <div class="form-row mb-3">
                        <div class="col">
                            {{ form.wysokosc|bootstrap }}
                        </div>
                        <div class="col">
                            {% if user.is_authenticated %}
                            <label class="control-label" for="id_data_serwis">Data serwisu</label>
                            <input type="date" id="id_data_serwis" name="data_serwis" class=" form-control">
                            {% endif %}
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Zapisz <i class="fas fa-save fa-lg"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/rozciagi/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'MDB-Free_4.15.0/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'MDB-Free_4.15.0/css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'MDB-Free_4.15.0/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'MDB-Free_4.15.0/css/addons/datatables.min.css' %}" rel="stylesheet">
    <link href="{% static 'fontawesome/css/all.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/rozciagi.css' %}">
    <title>..:: Rozciągi ::..</title>
</head>

templates/rozciagi/header.html
    <header>
        <!--Navbar -->
        <nav class="mb-1 navbar navbar-expand-lg navbar-dark unique-color-dark">
            <a class="navbar-brand" href="/">..:: Rozciągi ::..</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-555" aria-controls="navbarSupportedContent-555" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent-555">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/wszystkie">Wszystkie wpisy</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="/eksport">Eksport</a>
                        </li>
                    {% endif %}

                </ul>
                <ul class="navbar-nav ml-1 nav-flex-icons">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-4" data-toggle="dropdown"  aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user"></i> Profile
                        </a>
                        <div class="dropdown-menu dropdown-menu-right dropdown-info" aria-labelledby="navbarDropdownMenuLink-4">
                            {% if user.is_authenticated %}
                                <a class="dropdown-item" href="/admin">Moje konto</a>
                                <a class="dropdown-item" href="/logout">Logout <i class="fas fa-sign-out-alt fa-lg"></i></a>
                            {% else %}
                                <a class="dropdown-item" href="/login">Login <i class="fas fa-sign-in-alt fa-lg"></i></a>
                            {% endif %}
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
<!--/.Navbar -->
    </header>

templates/rozciagi/login.html
{% extends 'rozciagi/base.html' %}
{% load bootstrap %}
{% block content %}
    <div class="container-fluid">
        <div class="card col-md-6 my-3 mx-auto">
            <div class="card-body">
                <form method="post" role="form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|bootstrap }}
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Zaloguj <i class="fas fa-sign-in-alt fa-lg"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/rozciagi/messages.html
{% load bootstrap %}

{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'suuccess' %}
            <div class="alert alert-success col-md-6 mx-auto" role="alert">
                {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% elif message.tags == 'info' %}
            <div class="alert alert-info col-md-6 mx-auto" role="alert">
                {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% elif message.tags == 'warning' %}
            <div class="alert alert-warning col-md-6 mx-auto" role="alert">
                {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% elif message.tags == 'error' %}
            <div class="alert alert-danger col-md-6 mx-auto" role="alert">
                {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

templates/rozciagi/potwierdz.html
{% extends 'rozciagi/base.html' %}
{% load bootstrap %}
{% block content %}
    <div class="container-fluid">
        <div class="card col-md-6 my-3 mx-auto">
            <div class="card-body">
                <h1>Czy napewno chcesz usunąć wpis dla indeksu: {{ wpis.indeks_kontaktu }} ??</h1>
                <form method="POST" role="form" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <button type="submit" class="btn btn-danger">Tak <i class="far fa-check-square"></i></button> <a class="btn btn-primary" href="/" role="button">Nie <i class="fas fa-times"></i></a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/rozciagi/scripts.html
{% load static %}
    <!-- jQuery -->
    <script type="text/javascript" src="{% static 'MDB-Free_4.15.0/js/jquery.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'MDB-Free_4.15.0/js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'MDB-Free_4.15.0/js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'MDB-Free_4.15.0/js/mdb.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'MDB-Free_4.15.0/js/addons/datatables.min.js' %}"></script>
    <!-- Your custom scripts (optional) -->
    <script type="text/javascript">

        $(document).ready(function () {
            $('#paginationFull').DataTable({
                "id": [[ 3, "desc" ]],
                "pagingType": "full"
            });
            $('.dataTables_length').addClass('bs-select');
        });

    </script>

templates/rozciagi/test.html
{% extends 'rozciagi/base.html' %}
{% block content %}
<div class="container-fluid">

        <h1>Wszystkie wpisy</h1>


        <table class="table table-sm table-hover">
            <thead class="black white-text">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Indeks kontaktu</th>
                    <th scope="col">Przekroj przewodu</th>
                    <th scope="col">Rozciag</th>
                    <th scope="col">nr narzedzia</th>
                    <th scope="col">Rodzaj narzedzia</th>
                    <th scope="col">nr zlecenia</th>
                    <th scope="col">nr pracownika</th>
                    <th scope="col">uwagi</th>
                    <th scope="col">#</th>
                </tr>
            </thead>
            <tbody>
                {% for wpis in rozciag %}
                <tr>
                    <th scope="row">{{ wpis.id }}</th>
                    <td>{{ wpis.indeks_kontaktu }}</td>
                    <td>{{ wpis.przekroj_przewodu }}</td>
                    <td>{{ wpis.rozciag }}</td>
                    <td>{{ wpis.narzedzia }}</td>
                    <td>{{ wpis.narzedzia_rodzaj }}</td>
                    <td>{{ wpis.nr_zlecenia }}</td>
                    <td>{{ wpis.nr_pracownika }}</td>
                    <td>{{ wpis.uwagi }}</td>
                    <td><a href="{% url 'edytuj_wpis' wpis.id %}" class="btn btn-primary btn-sm mr-2">Edytuj</a> <a href="{% url 'usun_wpis' wpis.id %}" class="btn btn-primary btn-sm">Usun</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <nav aria-label="Page navigation example">
            <ul class="pagination pg-dark justify-content-center">
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1">Previous</a>
                </li>
                <li class="page-item">
                    <a class="page-link">1</a>
                </li>
                <li class="page-item active">
                    <a class="page-link">2 <span class="sr-only">(current)</span></a>
                </li>
                <li class="page-item">
                    <a class="page-link">3</a>
                </li>
                <li class="page-item">
                    <a class="page-link">Next</a>
                </li>
            </ul>
        </nav>
    </div>
{% endblock content %}

templates/rozciagi/wpisane.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'MDB-Free_4.15.0/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'MDB-Free_4.15.0/css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'MDB-Free_4.15.0/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'fontawesome/css/all.css' %}" rel="stylesheet">
    <title>Document</title>
</head>
<body class="d-flex flex-column h-100 d-inline-block">
    <header>
        <!--Navbar -->
        <nav class="mb-1 navbar navbar-expand-lg navbar-dark unique-color-dark">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-555" aria-controls="navbarSupportedContent-555" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent-555">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Pricing</a>
                    </li>
                </ul>
                <form class="form-inline">
                    <div class="md-form my-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    </div>
                </form>
                <ul class="navbar-nav ml-1 nav-flex-icons">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-4" data-toggle="dropdown"  aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user"></i> Profile
                        </a>
                        <div class="dropdown-menu dropdown-menu-right dropdown-info" aria-labelledby="navbarDropdownMenuLink-4">
                            <a class="dropdown-item" href="#">My account</a>
                            <a class="dropdown-item" href="#">Log out</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
<!--/.Navbar -->
    </header>
    <div class="container-fluid">

        <h1>Moja strona</h1>


        <table class="table table-sm table-hover">
            <thead class="black white-text">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">First</th>
                    <th scope="col">Last</th>
                    <th scope="col">Handle</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>Mark</td>
                    <td>Otto</td>
                    <td>@mdo</td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>Jacob</td>
                    <td>Thornton</td>
                    <td>@fat</td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td colspan="2">Larry the Bird</td>
                    <td>@twitter</td>
                </tr>
                <tr>
                    <th scope="row">1</th>
                    <td>Mark</td>
                    <td>Otto</td>
                    <td>@mdo</td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>Jacob</td>
                    <td>Thornton</td>
                    <td>@fat</td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td colspan="2">Larry the Bird</td>
                    <td>@twitter</td>
                </tr>
            </tbody>
        </table>
        <nav aria-label="Page navigation example">
            <ul class="pagination pg-dark justify-content-center">
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1">Previous</a>
                </li>
                <li class="page-item">
                    <a class="page-link">1</a>
                </li>
                <li class="page-item active">
                    <a class="page-link">2 <span class="sr-only">(current)</span></a>
                </li>
                <li class="page-item">
                    <a class="page-link">3</a>
                </li>
                <li class="page-item">
                    <a class="page-link">Next</a>
                </li>
            </ul>
        </nav>
    </div>
    <!-- Footer -->
    <footer class="page-footer font-small unique-color-dark pt-4">
        <!-- Footer Elements -->
        <div class="container">
            <!-- Call to action -->
            <ul class="list-unstyled list-inline text-center py-2">
                <li class="list-inline-item">
                    <h5 class="mb-1">Register for free</h5>
                </li>
                <li class="list-inline-item">
                    <a href="#!" class="btn btn-outline-white btn-rounded">Sign up!</a>
                </li>
            </ul>
            <!-- Call to action -->
        </div>
        <!-- Footer Elements -->
        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">© 2020 Copyright:
            <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->

  <!-- jQuery -->
  <script type="text/javascript" src="{% static 'MDB-Free_4.15.0/js/jquery.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'MDB-Free_4.15.0/js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'MDB-Free_4.15.0/js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'MDB-Free_4.15.0/js/mdb.min.js' %}"></script>
  <!-- Your custom scripts (optional) -->
  <script type="text/javascript"></script>

</body>
</html>

templates/rozciagi/wszystkie_wpisy.html
{% extends 'rozciagi/base.html' %}
{% block content %}

    <div class="container-fluid">
        <h1>Wszystkie wpisy</h1>

        <table id="paginationFull" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead class="black white-text">
                <tr>
                    <th class="th-sm">#</th>
                    <th class="th-sm">Indeks kontaktu</th>
                    <th class="th-sm">Rodzaj listy</th>
                    <th class="th-sm">Przekroj przewodu</th>
                    <th class="th-sm">Rozciag</th>
                    {% if user.is_authenticated %}
                    <th class="th-sm">Wysokość</th>
                    {% endif %}
                    <th class="th-sm">nr narzedzia</th>
                    <th class="th-sm">Rodzaj narzedzia</th>
                    <th class="th-sm">nr zlecenia</th>
                    <th class="th-sm">Poprawkowe</th>
                    <th class="th-sm">nr pracownika</th>
                    <th class="th-sm">Grupa Robocza</th>
                </tr>
            </thead>
            <tbody>
                {% for wpis in rozciag %}
                <tr>
                    <th scope="row">{{ wpis.id }}</th>
                    <td>{{ wpis.indeks_kontaktu }}</td>
                    <td>{{ wpis.lista }}</td>
                    <td>{{ wpis.przekroj_przewodu }}</td>
                    <td>{{ wpis.rozciag }}</td>
                    {% if user.is_authenticated %}
                    <td>{{ wpis.wysokosc }}</td>
                    {% endif %}
                    <td>{{ wpis.narzedzia }}</td>
                    <td>{{ wpis.narzedzia_rodzaj }}</td>
                    <td>{{ wpis.nr_zlecenia }}</td>
                    <td>{{ wpis.poprawkowe }}</td>
                    <td>{{ wpis.nr_pracownika }}</td>
                    <td>{{ wpis.grupa_robocza }}</td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot class="black white-text">
                <tr>
                    <th class="th-sm">#</th>
                    <th class="th-sm">Indeks kontaktu</th>
                    <th class="th-sm">Rodzaj listy</th>
                    <th class="th-sm">Przekroj przewodu</th>
                    <th class="th-sm">Rozciag</th>
                    {% if user.is_authenticated %}
                    <th class="th-sm">Wysokość</th>
                    {% endif %}
                    <th class="th-sm">nr narzedzia</th>
                    <th class="th-sm">Rodzaj narzedzia</th>
                    <th class="th-sm">nr zlecenia</th>
                    <th class="th-sm">Poprawkowe</th>
                    <th class="th-sm">nr pracownika</th>
                    <th class="th-sm">Grupa Robocza</th>
                </tr>
            </tfoot>
        </table>
    </div>

{% endblock content %}